### ISSUE TITLE
Hello! When are you planning to release the data? 

### ISSUE THREAD

**Issue by Xianjun-Yang** [amitakamath/whatsup_vlms#1]
Thanks!

**Comment by vishaal27** [comment]
I am interested too, thanks!

**Comment by pumpkin805** [comment]
I am interested too, thanks!

**Comment by WasedaMagina** [comment]
I am interested too, thanks!

**Comment by yusuketozaki** [comment]
I am interested too, thanks!

**Comment by bpiyush** [comment]
Hi @amitakamath ! Great work!

Is there an update on availability of the dataset?

Thanks!

**Comment by Avagr** [comment]
Seconding this.

The clean "What's Up" part could be really useful, and I am eagerly waiting for its release.

@amitakamath, any updates on this issue? Thanks!

**Comment by amitakamath** [comment]
@Xianjun-Yang @vishaal27 @pumpkin805 @WasedaMagina @Yusuke-TOZAKI @bpiyush @Avagr 

It's finally up! I'm so sorry for the delay, but here are the code and data. Please let me know if you have any questions or comments! 

I'll close this issue; feel free to open others as needed.

**Comment by bpiyush** [comment]
Thank you @amitakamath !
